### ISSUE TITLE
Job hangs at "Pushing first task to queue: setup" in Docker Compose Environment

### ISSUE THREAD

**Issue by tesso57** [Simply-Static/simply-static#293]
**Description:**  
When initiating a static export using Simply Static in our Docker Compose setup, the log output stops at:

```
Pushing first task to queue: setup
```

No further tasks (e.g., fetch_urls, create_zip_archive, wrapup) are processed afterward. This behavior has been observed even after multiple attempts.

**Environment:**  
We are running the latest official WordPress and MySQL images using the following Docker Compose file:

```yaml
version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: db_local 
      MYSQL_USER: wp_user 
      MYSQL_PASSWORD: password 
  WordPress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 10090:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password 
      WORDPRESS_DB_NAME: db_local
      WORDPRESS_DEBUG: 1 
    volumes:
      - ./html:/var/www/html
```

**Steps to Reproduce:**  
1. Use the above Docker Compose configuration to set up a local WordPress environment.
2. Install and configure the Simply Static plugin in the WordPress site.
3. Initiate a static export process.
4. Observe the logs; the output stops at `"Pushing first task to queue: setup"`.

**Expected Behavior:**  
After the "setup" task is pushed to the queue, subsequent tasks (fetch_urls, create_zip_archive, wrapup) should execute and complete the export.

**Questions:**  
- Are there any additional configuration steps or environment considerations needed when running Simply Static in a Docker environment?
- Is there any known issue with the current version of Simply Static when used in Docker Compose environments?

Any help or guidance to resolve this issue and ensure that the job completes would be greatly appreciated.
